---
- name: Install fail2ban drop-in
  ansible.builtin.template:
    src: templates/99-sshd.local.j2
    dest: /etc/fail2ban/jail.d/99-sshd.local
    owner: root
    group: root
    mode: 0644
  notify: restart-fail2ban

