---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install a few prerequisite packages which let apt use packages over HTTPS
  ansible.builtin.apt:
    name: 
     - apt-transport-https 
     - ca-certificates 
     - software-properties-common

- name: Add the GPG key for the official Docker repository to the server
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add the Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: 
      - docker-ce=27.5*
      - docker-ce-cli=27.5*
      - containerd.io=27.5*
      - docker-compose-plugin=2.*
    state: present
    update_cache: yes

